### PR TITLE
🎛️: fix spacing artefact on list scroll

### LINKED ISSUE #1475: Listitems are not evenly spaced when utilizing border value
image

To reproduce, you'll either need the new font aliases or a custom font added to the currently opened project.

### PR DESCRIPTION
**Pull request by merryman**
Fixes #1475.

### CODE REVIEW

File: lively.components/list.js [hunk 1]
```diff
@@ -125,7 +125,7 @@ export class ListItemMorph extends Label {
       // this is faster:
       if (item.autoFit) itemMorph.width = goalWidth;
       const width = itemMorph ? Math.max(itemMorph.width, goalWidth) : goalWidth;
-      const height = itemHeight + this.borderWidth.bottom + this.borderWidth.top; // itemMorph ? Math.max(itemMorph.height, itemHeight) : itemHeight;
+      const height = itemHeight + this.borderWidth.bottom + this.borderWidth.top; // FIXME: this causes funny issues in placement of the morphs
```
Comment (linusha) [inline lively.components/list.js:128]:
```suggestion
      const height = itemHeight + this.borderWidth.bottom + this.borderWidth.top;
```

File: lively.components/list.js [hunk 2]
```diff
@@ -780,7 +780,9 @@ export class List extends Morph {
 
       itemMorphs = [...lower, ...rest, ...upper];
 
-      let borderOffsetForHeight = 0;
+      // retrieve border offset of item(s) that are already scrolled out of view
+      // but still affect the positioning of subsequent item morphs
```
Comment (linusha) [inline lively.components/list.js:784]:
```suggestion
      // retrieve border offset of item(s) that are already scrolled out of view but still affect the positioning of subsequent item morphs
```

**Review by linusha — CHANGES_REQUESTED** [review]
Just cosmetic stuff. Otherwise this is working as intended. Nice one :rocket:
